### PR TITLE
Require package

### PR DESCRIPTION
**Pull request by tasshin**
Based on @purcell's comments in #3.

### CODE REVIEW

**Comment by expez** [comment]
This looks good. Are you still working on this branch or do you want me to merge it in so you can base the other pr on master?

**Comment by tasshin** [comment]
@expez I'd like to 
a) have someone else run it and make sure everything still works.
b) have someone tell me that everything in site-lisp needs to be there (that is, needs to be there for clj-refactor)

Then I'd like to squash the commit.

Come to think of it, is it really true that we need a non-stable clj-refactor? It says on the project page that it is on MELPA stable.

**Comment by expez** [comment]
melpa stable is pretty damn old for clj-refactor.  We want to get 1.0 out the door with a gazillion new features, but we also want to make sure it's actually worth using.

**Comment by expez** [comment]
Looks to me like `company`, `epl` and `pkg-info` can be deleted.

Unfortunately I don't have time to try this out atm, I have to run.

**Comment by benedekfazekas** [comment]
i think we need company for completion in cider tho

**Comment by arrdem** [comment]
We do.

**Comment by expez** [comment]
If cider is installed by the package manager then so are its deps.

**Comment by purcell** [comment]
> If cider is installed by the package manager then so are its deps.

`cider` doesn't depend on `company`. There would need to be a separate `(require-package 'company)` to ensure it gets installed.

**Comment by benedekfazekas** [comment]
not sure company is a cider dependency. u still need it if u want proper
completion tho

**Comment by benedekfazekas** [comment]
happy to test this tmrw morning. can't do this evening unfortunately

**Comment by ghost** [comment]
i will also test tomorrow

**Comment by expez** [comment]
right, forgot about `company` being a soft dependency for cider, but why not install `company` as well through the package manager?

**Comment by benedekfazekas** [comment]
tested with 24.3 and 24.4. essentially the inital require package works fine at startup. there is one issue tho and two request:
1. apparently this line `(add-to-list 'load-path (concat user-emacs-directory "site-lisp"))` does not really work. I had to add all directories under `.emacs.d/site-lisp` to the load path to make clj-refactor work. I know this is suboptimal (lovely word 'suboptimal') but there is a good reason, see @expez and my previous comments
2. could you pls extend the 'Using Emacs package management' section in README specially explaining what happens at first start up
3. exec-path-from-shell comes from stable now init.el initial comment needs fixing.

ta!

**Comment by tasshin** [comment]
I'll fix those things soon, @benedekfazekas.

My last commit anticipated @expez's suggestion, and does a require-package on company, too.

How would we feel about doing that with all of clj-refactor's dependencies (if they are available on MELPA stable)?

**Comment by benedekfazekas** [comment]
that is cool for company.

but as @expez said above unfortunately melpa stable has a dated clj-refactor version. as soon as clj-refactor 1.0.0 released to melpa stable i will get rid of the ugly load path hacking here i promise ;)

hope this answers your question. ta for the good work

**Comment by tasshin** [comment]
@benedekfazekas, sorry, I meant doing the same for everything but clj-refactor and anything else that we need an unstable version of.

From a first glance on Melpa stable, It looks like that'd be everything but clj-refactor and s.el.

**Comment by benedekfazekas** [comment]
yeah just reread your comment and realised i misunderstood. sry. yeah right, why not: perhaps mark them in comment that they are dependencies of refactor? (so i can remove them easily when we can do proper require-package for clj-refactor)

**Comment by tasshin** [comment]
OK, I'll try to add a comment about that. And it looks like we need to grab yasnippet manually, too. So I'll keep that, s.el, and clj-refactor.

**Comment by benedekfazekas** [comment]
sounds like a good middleground. thx

**Comment by tasshin** [comment]
OK, I think this should be functional and ready to go (after a squash or two).

I took the liberty of taking my big red pen to the README in the last commit.

**Comment by ghost** [comment]
I just downloaded your latest commit @mwfogleman from your branch, made it my .emacs.d/ dir (after having previously renamed my existing .emacs.d to a backup) and opened my Emacs 24.3.1 on OSX. The following warnings/errors occurred:

Warning (emacs): Unable to activate package `pkg-info'.
Required package`dash-1.6.0' is unavailable
Warning (initialization): An error occurred while loading `/Users/hellofunk/.emacs.d/init.el':

File error: Cannot open load file, clj-refactor

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by tasshin** [comment]
OK, thanks for testing @hellofunk! Not sure what the problem is but I'll look into it.

**Comment by benedekfazekas** [comment]
yup, same here: no joy. this works for me tho (tested both 24.3 and 24.4):

``` elisp
(add-to-list 'load-path (concat user-emacs-directory "site-lisp/s-20140910.334"))
(add-to-list 'load-path (concat user-emacs-directory "site-lisp/yasnippet-20141223.303"))
(add-to-list 'load-path (concat user-emacs-directory "site-lisp/clj-refactor-20150104.1358"))
```

**Comment by tasshin** [comment]
@benedekfazekas Aha, I forgot the /. My bad. Pushed an update.

**Comment by ghost** [comment]
These various issues and warnings that have popped up in the building of this example config certainly validate the need for this config in the first place! If you seasoned emacs users have problems with this stuff, imagine how nearly impossible it is for a newbie to get it all going! @mwfogleman I till try your latest right now.

**Comment by benedekfazekas** [comment]
all good. will merge as soon as you squash. special thx for big red pen corrections ;)

**Comment by ghost** [comment]
hm, still having errors.

i simply downloaded the zip file from here:

https://github.com/mwfogleman/example-config/tree/require-package

right place?

i still get these errors on emacs startup:

pkg-info.el:48:1:Error: Cannot open load file: dash
Warning (emacs): Unable to activate package `pkg-info'.
Required package`dash-1.6.0' is unavailable

however, when I closed emacs and then started it again, there were no errors reported.

**Comment by benedekfazekas** [comment]
i've seen that error pop up now and then but cljrefactor and cider was still functional (they use dash i think) so i guess nothing to worry about...

**Comment by tasshin** [comment]
I squashed my commits.

**Pull request merged**
